EventSafari/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('services/', include('organizer.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('khalti/', include('khalti.urls')),
] 

main/urls.py
from django.contrib import admin
from django.views.generic import TemplateView, FormView, ListView, UpdateView, DeleteView, DetailView, CreateView
from django.urls import path, include
from . import views
from django.contrib import admin
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from .views import SearchResultsList

urlpatterns = [
   
   
    
    path('', views.Index, name="index"),
    #path('search/', views.search, name="search"),
    
    path("search/", SearchResultsList.as_view(), name="search_results"),

    path('eventcategory/', views.eventcategory, name="eventcategory"),
    path('category/<int:id>', views.ReadCat, name="event-cat"),

    #path('listevents/', views.ListEvents.as_view(), name="listevents"),
    path('listevents/', views.event_list, name="listevents"),
    path('eventdetail/<int:event_id>/', views.event_detail, name="eventdetail"),
    path('addtocart/<int:id>/', views.addToCart, name="addtocart"),
    path('displaycart/', views.DisplayCart.as_view(), name="displaycart"),
    path('updatecart/<int:pk>/', views.UpdateCart.as_view(), name="updatecart"),
    path('deletefromcart/<int:pk>/', views.DeleteFromCart.as_view(), name="deletefromcart"),
    path('checkout', views.checkout, name='checkout'),

    #path('api/listeventsapi/', views.listEventsApi, name="listeventsapi"),
   # path('api/suggestionapi/', views.suggestionApi, name="suggestionapi"),


    #authentication endpoints
    path('signup/', views.RegisterView.as_view(), name='signup'),
    path('login/', views.LoginViewUser.as_view(), name="login"),
    path('logout/', views.LogoutViewUser.as_view(), name="logout"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),


    # change password
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='main/authentication/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='main/authentication/password_change.html', success_url = reverse_lazy("password_change_done")), 
        name='password_change'),

    #Forgot password
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name = "main/authentication/password_reset_form.html", success_url = reverse_lazy("password_reset_complete")), 
    name="password_reset_confirm"),  # 3
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name = "main/authentication/password_reset.html", success_url = reverse_lazy("password_reset_done"), email_template_name = 'main/authentication/forgot_password_email.html'), 
    name="reset_password"),     # 1
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name = "main/authentication/password_reset_sent.html"), 
    name="password_reset_done"),    # 2
    
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name = "main/authentication/password_reset_done.html"), 
    name="password_reset_complete"),   # 4
    

    path('profile/', views.profile, name='profile'),

    
    path('initiate-payment/', views.initiate_payment, name='initiate_payment'),
    path('payment-callback/', views.payment_callback, name='payment_callback'),
    path('payment-failure-callback/', views.payment_failure_callback, name='payment_failure_callback'),


]

urlpatterns += static(settings.MEDIA_URL ,document_root = settings.MEDIA_ROOT)

main/models.py
import uuid

from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from PIL import Image
from django.utils.translation import gettext_lazy as _
from multiselectfield import MultiSelectField
from django.core.validators import RegexValidator
from django.urls import reverse


from django.db.models import Q
from tinymce import models as tinymce_models
from datetime import timedelta

import zoneinfo


from phonenumber_field.modelfields import PhoneNumberField

from .manager import CustomUserManager


class LowercaseEmailField(models.EmailField):
    def to_python(self, value):
        value = super(LowercaseEmailField, self).to_python(value)
        # Value can be None so check that it's a string before lowercasing.
        if isinstance(value, str):
            return value.lower()
        return value

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = LowercaseEmailField(_('email address'), unique=True)
    name = models.CharField(null=True, blank=True, max_length=255)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    
    class Types(models.TextChoices):
        ORGANIZER = "Organizer", "ORGANIZER"
        AUDIENCE = "Audience", "AUDIENCE"
        

    default_type = Types.AUDIENCE

    type = MultiSelectField(choices=Types.choices, default=[], null=True, blank=True, max_length=20)
    

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return f"{self.id}: {self.email}"

    def save(self, *args, **kwargs):
        if not self.id:
            self.type.append(self.default_type)
        return super().save(*args, **kwargs)


class AudienceAdditional(models.Model):
    user = models.OneToOneField(CustomUser, on_delete = models.CASCADE)
    profile_picture = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.name} Profile'

    # Override the save method of the model
    def save(self):
        super().save()

        img = Image.open(self.image.path) # Open image

        # resize image
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size) # Resize image
            img.save(self.image.path) # Save it again and override the larger image 

            
class OrganizerAdditional(models.Model):
    user = models.OneToOneField(CustomUser, on_delete = models.CASCADE)
    address = models.CharField(max_length=255)
    website_url = models.URLField(max_length=200, blank=True)
    profile_picture = models.ImageField(default='default.jpg', upload_to='profile_pics')
    description = models.TextField(blank=True, null=True)
    social_media_link = models.URLField(blank=True, null=True)
    phone = PhoneNumberField()

    

    
# Model Managers for proxy models
class OrganizerManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        #return super().get_queryset(*args, **kwargs).filter(type = CustomUser.Types.SELLER)
        return super().get_queryset(*args, **kwargs).filter(Q(type__contains = CustomUser.Types.ORGANIZER))

class AudienceManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        #return super().get_queryset(*args, **kwargs).filter(type = CustomUser.Types.CUSTOMER)
        return super().get_queryset(*args, **kwargs).filter(Q(type__contains = CustomUser.Types.AUDIENCE))
       


# Proxy Models. They do not create a seperate table
class Organizer(CustomUser):
    default_type = CustomUser.Types.ORGANIZER
    objects = OrganizerManager()
    class Meta:
        proxy = True
    
    def create(self):
        print("I can create")

    @property
    def showAdditional(self):
        return self.organizeradditional

class Audience(CustomUser):
    default_type = CustomUser.Types.AUDIENCE
    objects = AudienceManager()
    class Meta:
        proxy = True 

    def book(self):
        print("I can book")

    @property
    def showAdditional(self):
        return self.audienceadditional

class Category(models.Model):
    cat_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150,db_index=True)
    
    def __str__(self):
        return self.name
    

class Event(models.Model):
    event_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=150)
    event_description = tinymce_models.HTMLField() 
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(default=timezone.now)
    start_time = models.TimeField(default=timezone.now)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    venue = models.CharField(max_length=150)
    capacity = models.IntegerField()
    image = models.ImageField(default="default_banner.png", upload_to="event_images")
    price = models.FloatField(default=0)
    organizer = models.ForeignKey(Organizer, related_name='organizer', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
	     return self.title
   



class CartManager(models.Manager):
    def create_cart(self, user):
        cart = self.create(user = user)
        return cart

class Cart(models.Model):
    cart_id = models.AutoField(primary_key=True)
    user = models.OneToOneField(CustomUser, on_delete = models.CASCADE)
    created_on = models.DateTimeField(default=timezone.now)

    objects = CartManager()

    def subtotal(self):
        events_in_cart = EventInCart.objects.filter(cart=self)
        total = 0
        for event_in_cart in events_in_cart:
            total += event_in_cart.event.price * event_in_cart.quantity
        return total

    def __str__(self):
	    return f"Cart for {self.user.name}"

class EventInCart(models.Model):
    class Meta:
        unique_together = (('cart', 'event'),)
    event_in_cart_id = models.AutoField(primary_key=True)
    cart = models.ForeignKey(Cart, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, on_delete = models.CASCADE)
    quantity = models.PositiveIntegerField()


    def __str__(self):
	     return f"Event: {self.event.title}"


class Payment(models.Model):
    pidx = models.CharField(max_length=100)
    transaction_id = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    mobile = models.CharField(max_length=20)
    purchase_order_id = models.CharField(max_length=100)
    purchase_order_name = models.CharField(max_length=100)
    status = models.CharField(max_length=20)

'''

class OtpModel(models.Model):
    otp_regex = RegexValidator( regex = r'^\d{6}$',message = "otp should be in six digits")
    otp = models.CharField(max_length=6, validators=[otp_regex])
    phone_regex = RegexValidator( regex = r'^\d{10}$',message = "phone number should exactly be in 10 digits")
    phone = models.CharField(max_length=255, validators=[phone_regex])
    expiry = models.DateTimeField(default = (timezone.now() + timedelta(minutes = 5)))
    is_verified = models.BooleanField(default=False)
    
'''    

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, ReadOnlyPasswordHashField
from .models import CustomUser, Organizer, OrganizerAdditional, Event, EventInCart, AudienceAdditional
from django.core.exceptions import ValidationError 
from django.core.validators import RegexValidator
import zoneinfo

from bootstrap_datepicker_plus.widgets import DatePickerInput, TimePickerInput

from timezone_field import TimeZoneFormField
from tinymce.widgets import TinyMCE

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

class AudienceProfileForm(forms.ModelForm):
    class Meta:
        model = AudienceAdditional
        fields = ['profile_picture']

        
class RegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = [
            'email',
            'name',
            'password1',
            'password2',
        ]

'''
class RegistrationFormSeller(UserCreationForm):
    
    phone_regex = RegexValidator( regex = r'^\d{10}$',message = "phone number should exactly be in 10 digits")
    phone = forms.CharField(max_length=255, validators=[phone_regex])
    timezone = TimeZoneFormField(choices_display="WITH_GMT_OFFSET")
    class Meta:
        model = Organizer
        fields = [
            'email',
            'name',
            'password1',
            'password2',
            'phone',
            'timezone'
        ]        
'''

class RegistrationFormSeller2(forms.ModelForm):
    class Meta:
        model = OrganizerAdditional
        fields = [
            'phone',
            'address',
        ]

class EventCreation(forms.ModelForm):
    class Meta:
        model = Event
        widgets = {'content': TinyMCE(attrs={'cols': 40, 'rows': 20}),
                   "start_date": DatePickerInput(),
                   "end_date": DatePickerInput(range_from="start_date"),
                   "start_time": TimePickerInput(),
                   }
        fields = [
            'title',
            'event_description',
            'start_date',
            'end_date',
            'start_time',
            'category',
            'venue',
            'capacity',
            'image',
            'price'
        ]


class CartForm(forms.ModelForm):
    class Meta:
        model = EventInCart
        fields = [
            'quantity'
        ]

class PaymentForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    phone = forms.CharField(max_length=20)
    amount = forms.DecimalField(max_digits=10, decimal_places=2)
'''
class SendOtpBasicForm(forms.Form):
    phone_regex = RegexValidator( regex = r'^\d{10}$',message = "phone number should exactly be in 10 digits")
    phone = forms.CharField(max_length=255, validators=[phone_regex])

    class Meta:
        fields = [
            'phone',
        ]

class VerifyOtpBasicForm(forms.Form):
    otp_regex = RegexValidator( regex = r'^\d{4}$',message = "otp should be in six digits")
    otp = forms.CharField(max_length=6, validators=[otp_regex])

    # class Meta:
    #     field




'''

templates/main/basic.html
<!doctype html>
<html lang="en">
{% load static %}  
{% load hosts %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap package -->
    <title>{% block title %}{% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css?family=Roboto|Acme|Rubik|Kanit|Quicksand" rel="stylesheet"/>
    
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.min.css" rel="stylesheet"/>

   

    <!-- Custom CSS -->
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">

    
    {% block css %}
    {% endblock %}

</head>

<body>
  
    

    {% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" style="margin-bottom:0px;">
             {{ message|safe }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
         </div>
     {% endfor %}
    {% endif %}


 {% block body %}
 
 {% endblock %}

    

    <!-- Bootstrap Bundle with Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-popRpmFF9JQgExhfw5tZT4I9/CI5e2QcuUZPOVXb1m7qUmeR2b50u+YFEYe1wgzy"
        crossorigin="anonymous"></script>
    
    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.umd.min.js"></script> 

     <!--HTMX-->
     <script src="https://unpkg.com/htmx.org@1.9.9" integrity="sha384-QFjmbokDn2DjBjq+fM+8LUIVrAgqcNW2s0PjAxHETgRn9l4fvX31ZxDxvwQnyMOX" crossorigin="anonymous"></script>


</body>

{% block js %}
{% endblock %}

</html>

templates/main/checkout.html
{% extends 'main/basic.html' %}
{% load hosts %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
{% endblock %}

{% block body%}
<div class="container p-5 m-5 text-success border custom-text-2">
    <h3>Checkout</h3>
    <hr>
    <h5>How would you like to pay?</h5>
    <a class="btn custom-btn-2 my-5" href="#" role="button">Card</a>
    <a class="btn custom-btn-2 my-5" href="#" role="button">Khalti</a>
    <hr>
    <h5>Card Details</h5>

    <form>
        <div class="row mb-3">
          <label for="exampleInputEmail1" class="col-sm-2 col-form-label">Card Number</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
          </div>
        </div>
        <div class="row mb-3">
            <label for="exampleInputEmail1" class="col-sm-2 col-form-label">Expiry Date</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
          </div>
          <div class="row mb-3">
            <label for="exampleInputEmail1" class="col-sm-2 col-form-label">Security Code</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
          </div>
        
          <a class="btn custom-btn-3 my-10 text-light" href="#" role="button">Purchase</a>
      </form>

</div> 

{% endblock %}

templates/main/displaycart.html
{% extends 'main/basic.html' %}
{% load hosts %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
  .main-area {
    padding-left: 20px;
    padding-right: 20px;
    padding-top: 0px;
    background-color: #f8f9fa;
  }

  .product-cards {
    background-color: white;
    padding: 10px;
    
  }
  .featurette{
    border: 0.5px solid rgb(236, 229, 229);
    border-radius: 20px;
    max-width: 500px;
    margin-left: 350px;
    padding: 30px;
  }

  .btn-primary {
    margin: 10px;
  }

  .custom-btn-4{
    border: 2px solid red;
    border-radius: 10px;
    font-family: Rubik !important;
    color: red;
    font-weight: 500;
  }
  .total{
    margin: auto;
    width: 25%;
  }
  
</style>
{% endblock %}

{% block body%}
 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg bg-body-tertiary custom-text-4">
  <!-- Container wrapper -->
  <div class="container">
      <!-- Toggle button -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="fas fa-bars"></span>
      </button>


      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Navbar brand -->
          <a class="navbar-brand mt-2 mt-lg-0" href="#">
              <b>EventSafari</b>
          </a>
          

          
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->


<div class="main-area">
  <div class="product-cards">
    <h3 style="text-align:center; font-family: Quicksand; color: #006241;"> Your Cart</h3>

    {% for i in cart %}
    <div class="row featurette">
      <div class="col-md-2">
        <img src="/media/{{i.event.image}}" class="card-img-top" alt="...">
      </div>
      <div class="col-md-7">
        <h2 class="featurette-heading">{{i.event.event_name}}</h2>
        <p class="lead">{{i.event.title}}</p>
        <p class="lead">Rs. {{i.event.price}}</p>
        <p class="lead">Ticket Quantity- {{i.quantity}}</p>
        <form method="POST" action="{% url 'updatecart' pk=i.event_in_cart_id %}">{% csrf_token %}
          <input type="text" id="id_quantity" name="quantity">
          <br>
          <br>
          <button class="btn custom-btn-1" type="submit">Update Quantity</button>
        </form>
        <br>
        <form method="POST" action="{% url 'deletefromcart' pk=i.event_in_cart_id %}">{% csrf_token %}
          <button class="btn custom-btn-4" type="submit">Delete</button>
        </form>
      </div>

    </div>
    <hr>
    {% empty %}
    <h4>Empty Cart</h4>
    {% endfor %}

    
  </div>
  <div class="container total">
  <h4 class="custom-text-2">Subtotal: Rs.{{ subtotal }}</h4><br>
  <a href="{% url 'checkout' %}" class="btn btn-lg custom-btn-3 mb-5" role="button">Checkout Now!</a>
  </div>
</div>
{% endblock %}

templates/main/event_detail.html
{% extends 'main/basic.html' %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
    .main-area {
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 0px;
        background-color: #f8f9fa;
    }

    .product-cards {
        background-color: white;
        padding: 10px;
    }

    body {
        background-color: #e0ebe7;
    }

    h4 {
        margin-left: 70px;
    }

    .book {
        margin-left: 100px;
    }

    .contact {
        margin-left: 15px;
    }

    .title {
        background-color: #f0f4f3;
    }
</style>
{% endblock %}

{% block body%}


<div class="container-fluid bg-light custom-text-4 shadow-5-strong title">
    <div class="row">
        <div class="col-9 custom-text-1 p-3">
            <h4><b>{{event.title}}</b></h4>
        </div>
        <div class="col-3 text-success p-3">
            <a href="{% url 'addtocart' id=event.event_id %}"> <button type="button" class="btn custom-btn-1 book">Book
                    Now</button></a>
        </div>
    </div>
</div>

<!-- Section: Split screen -->
<section class="">

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8">


                <div class="container m-5 custom-text-4">
                    <div class="container-fluid">
                        <img src="/media/{{event.image}}" class="img-fluid mx-auto d-block" alt="...">
                    </div>
                    <div class="container-fluid p-3">
                        <h6>ABOUT</h6>
                        <p>
                            {{event.event_description}}
                        </p>

                        <br>

                        <h6>DATE</h6>
                        <p>
                            {{event.start_date}}
                        </p>

                        <br>

                        <h6>LOCATION</h6>
                        <p>
                            {{event.venue}}
                        </p>
                    </div>

                    <a class="btn custom-btn-2 contact" href="#" role="button">Contact Organizer</a>
                </div>
            </div>



            <div class="col-lg-3 vh-100 m-5">

                <h5 class="text-center custom-text-1"><b>Similar Events</b></h5>



                <div class="row p-4 mb-5">

                    {% for rec_event in recommended_events %}

                    <div class="col mb-3">
                        <div class="card h-100 shadow-5-strong">
                            {% if rec_event.image %}
                            <img src="/media/{{ rec_event.image }}" alt="{{ rec_event.title }} Image">
                            {% endif %}
                            <div class="card-body">
                                <strong>{{ rec_event.title }}</strong>

                                {% if rec_event.venue %}
                                <p class="card-text"> <i class="fas fa-location-dot me-2 icon-color"></i>{{ rec_event.venue|join:" " }}</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}


                </div>
            </div>
        </div>

</section>
<!-- Section: Split screen -->


{% endblock %}

templates/main/eventcategory.html
{% extends 'main/basic.html' %}
{% load static %}
{% load hosts %}
{% block title %}
{% endblock %}
{% block css %}

{% endblock %}

{% block body%}




<div class="container">
    <div class="row">
 {% for i in cat %}
 <div class="col">
 <a href="{% url 'event-cat' i.cat_id %}" hx-get="{% url 'event-cat' i.cat_id %}" hx-target="#main-content">{{i.name}}</a><br>
 </div>
 {% endfor %}
 </div>
 </div>
 <div id="main-content" class="container pt-4"></div>
{% endblock %}

templates/main/login.html
{% extends 'main/basic.html' %}
{% load hosts %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
    


    #intro {
        background-image: url("/media/images/login-bg.jpg");
        height: 100vh;
    }


    

    .main-area {
        display: flex;
        align-items: center;
        margin-top: 100px;
    }

    .register-form {
        width: 100%;
        max-width: 400px;
        margin: auto;
        padding: 20px;
        border-radius: 5px;
        color: white;
    }

    .mainheading {
        text-align: center;
        color: white;
    }

    .form-control{
        background: rgba(74, 77, 74, 0.3);
    }

    .form-control:hover{
        background: rgba(74, 77, 74, 0.3);
    }

    .form-control::placeholder {
    color: white;
}

    .errorlist {
        color: red;
    }

    
</style>
{% endblock %}

{% block body%}
<div id="intro" class="bg-image shadow-2-strong">
    <div class="mask d-flex align-items-center h-100" style="background-color: rgba(0, 0, 0, 0.8);">
        <div class="container">
            <div class="row justify-content-center custom-text-4">
                <div class="col-xl-5 col-md-8">

                    <form method="POST">{% csrf_token %}
                        <div class="main-area">
                            <div class="register-form text-center">
                                {{ form.non_field_errors }}
                                <h2 class="mainheading">Welcome Back!</h2>
                                <p class="mainheading">Enter your email and password to Login.</p>
                                <br>
                                {{ form.username.errors }}
                                {{ form.username|addclass:'form-control'|addplaceholder:'Enter your email address'}}
                                <br>

                                {{ form.password.errors }}
                                {{ form.password|addclass:'form-control'|addplaceholder:' Enter your password' }}
                                <br>
                                <a href="{% host_url 'reset_password' host 'www' %}"><b>Forgot Password</b></a>
                                <br>
                                <br>
                                <button type="submit" class="btn custom-btn-1" style="width:360px"><b>Log In</b></button>
                                
                                <br>
                                <br>
                                Don't have an account? Create <a
                                    href="{% host_url 'signup' host 'www' %}"><strong>here</strong></a>!
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<!--
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
    <path fill="#7ea45e" fill-opacity="1" d="M0,64L40,96C80,128,160,192,240,234.7C320,277,400,299,480,304C560,309,640,299,720,261.3C800,224,880,160,960,122.7C1040,85,1120,75,1200,85.3C1280,96,1360,128,1400,144L1440,160L1440,320L1400,320C1360,320,1280,320,1200,320C1120,320,1040,320,960,320C880,320,800,320,720,320C640,320,560,320,480,320C400,320,320,320,240,320C160,320,80,320,40,320L0,320Z"></path>
  </svg>
-->
{% endblock %}

templates/main/sessiontesting.html
{% extends 'main/basic.html' %}
{% load static %}
{% block title %}
{% endblock %}
{% block css %}
{% endblock %}

{% block body%}
{% if user.is_authenticated %}
<h1>{{user.name}}</h1>
{% endif %}
{{ request.session.test }}
{{ request.session.test2 }}
{% endblock %}