EventSafari/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('services/', include('organizer.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('khalti/', include('khalti.urls')),
] 

main/urls.py
from django.contrib import admin
from django.views.generic import TemplateView, FormView, ListView, UpdateView, DeleteView, DetailView, CreateView
from django.urls import path, include
from . import views
from django.contrib import admin
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from .views import SearchResultsList

urlpatterns = [
   
   
    
    path('', views.Index, name="index"),
    #path('search/', views.search, name="search"),
    
    path("search/", SearchResultsList.as_view(), name="search_results"),

    path('eventcategory/', views.eventcategory, name="eventcategory"),
    path('category/<int:id>', views.ReadCat, name="event-cat"),

    #path('listevents/', views.ListEvents.as_view(), name="listevents"),
    path('listevents/', views.event_list, name="listevents"),
    path('eventdetail/<int:event_id>/', views.event_detail, name="eventdetail"),
    path('addtocart/<int:id>/', views.addToCart, name="addtocart"),
    path('displaycart/', views.DisplayCart.as_view(), name="displaycart"),
    path('updatecart/<int:pk>/', views.UpdateCart.as_view(), name="updatecart"),
    path('deletefromcart/<int:pk>/', views.DeleteFromCart.as_view(), name="deletefromcart"),
    path('checkout', views.checkout, name='checkout'),

    #path('api/listeventsapi/', views.listEventsApi, name="listeventsapi"),
   # path('api/suggestionapi/', views.suggestionApi, name="suggestionapi"),


    #authentication endpoints
    path('signup/', views.RegisterView.as_view(), name='signup'),
    path('login/', views.LoginViewUser.as_view(), name="login"),
    path('logout/', views.LogoutViewUser.as_view(), name="logout"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),


    # change password
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='main/authentication/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='main/authentication/password_change.html', success_url = reverse_lazy("password_change_done")), 
        name='password_change'),

    #Forgot password
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name = "main/authentication/password_reset_form.html", success_url = reverse_lazy("password_reset_complete")), 
    name="password_reset_confirm"),  # 3
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name = "main/authentication/password_reset.html", success_url = reverse_lazy("password_reset_done"), email_template_name = 'main/authentication/forgot_password_email.html'), 
    name="reset_password"),     # 1
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name = "main/authentication/password_reset_sent.html"), 
    name="password_reset_done"),    # 2
    
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name = "main/authentication/password_reset_done.html"), 
    name="password_reset_complete"),   # 4
    

    path('profile/', views.profile, name='profile'),

    
    path('initiate-payment/', views.initiate_payment, name='initiate_payment'),
    path('payment-callback/', views.payment_callback, name='payment_callback'),
    path('payment-failure-callback/', views.payment_failure_callback, name='payment_failure_callback'),


]

urlpatterns += static(settings.MEDIA_URL ,document_root = settings.MEDIA_ROOT)

organizer/urls.py
from django.urls import path
from . import views
from .views import EventCreationView, update_view, delete_view

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.RegisterView.as_view(), name="signup"),
    path('signuporganizer/', views.RegisterViewSeller.as_view(), name="signuporganizer"),
    path('login/', views.LoginViewUser.as_view(), name="login"),
    path('logout/', views.LogoutViewUser.as_view(), name="logout"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('home/', views.home, name="home"),
    path('events/', views.events, name="events"),
    path('create/', EventCreationView.as_view(),name='event-create'),
    path('<event_id>/edit/', update_view, name='edit_event'),
    path('<event_id>/delete/', delete_view, name='delete_event'),
    
]

urlpatterns += static(settings.MEDIA_URL ,document_root = settings.MEDIA_ROOT)

main/models.py
import uuid

from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from PIL import Image
from django.utils.translation import gettext_lazy as _
from multiselectfield import MultiSelectField
from django.core.validators import RegexValidator
from django.urls import reverse


from django.db.models import Q
from tinymce import models as tinymce_models
from datetime import timedelta

import zoneinfo


from phonenumber_field.modelfields import PhoneNumberField

from .manager import CustomUserManager


class LowercaseEmailField(models.EmailField):
    def to_python(self, value):
        value = super(LowercaseEmailField, self).to_python(value)
        # Value can be None so check that it's a string before lowercasing.
        if isinstance(value, str):
            return value.lower()
        return value

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = LowercaseEmailField(_('email address'), unique=True)
    name = models.CharField(null=True, blank=True, max_length=255)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    
    class Types(models.TextChoices):
        ORGANIZER = "Organizer", "ORGANIZER"
        AUDIENCE = "Audience", "AUDIENCE"
        

    default_type = Types.AUDIENCE

    type = MultiSelectField(choices=Types.choices, default=[], null=True, blank=True, max_length=20)
    

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return f"{self.id}: {self.email}"

    def save(self, *args, **kwargs):
        if not self.id:
            self.type.append(self.default_type)
        return super().save(*args, **kwargs)


class AudienceAdditional(models.Model):
    user = models.OneToOneField(CustomUser, on_delete = models.CASCADE)
    profile_picture = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.name} Profile'

    # Override the save method of the model
    def save(self):
        super().save()

        img = Image.open(self.image.path) # Open image

        # resize image
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size) # Resize image
            img.save(self.image.path) # Save it again and override the larger image 

            
class OrganizerAdditional(models.Model):
    user = models.OneToOneField(CustomUser, on_delete = models.CASCADE)
    address = models.CharField(max_length=255)
    website_url = models.URLField(max_length=200, blank=True)
    profile_picture = models.ImageField(default='default.jpg', upload_to='profile_pics')
    description = models.TextField(blank=True, null=True)
    social_media_link = models.URLField(blank=True, null=True)
    phone = PhoneNumberField()

    

    
# Model Managers for proxy models
class OrganizerManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        #return super().get_queryset(*args, **kwargs).filter(type = CustomUser.Types.SELLER)
        return super().get_queryset(*args, **kwargs).filter(Q(type__contains = CustomUser.Types.ORGANIZER))

class AudienceManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        #return super().get_queryset(*args, **kwargs).filter(type = CustomUser.Types.CUSTOMER)
        return super().get_queryset(*args, **kwargs).filter(Q(type__contains = CustomUser.Types.AUDIENCE))
       


# Proxy Models. They do not create a seperate table
class Organizer(CustomUser):
    default_type = CustomUser.Types.ORGANIZER
    objects = OrganizerManager()
    class Meta:
        proxy = True
    
    def create(self):
        print("I can create")

    @property
    def showAdditional(self):
        return self.organizeradditional

class Audience(CustomUser):
    default_type = CustomUser.Types.AUDIENCE
    objects = AudienceManager()
    class Meta:
        proxy = True 

    def book(self):
        print("I can book")

    @property
    def showAdditional(self):
        return self.audienceadditional

class Category(models.Model):
    cat_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150,db_index=True)
    
    def __str__(self):
        return self.name
    

class Event(models.Model):
    event_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=150)
    event_description = tinymce_models.HTMLField() 
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(default=timezone.now)
    start_time = models.TimeField(default=timezone.now)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    venue = models.CharField(max_length=150)
    capacity = models.IntegerField()
    image = models.ImageField(default="default_banner.png", upload_to="event_images")
    price = models.FloatField(default=0)
    organizer = models.ForeignKey(Organizer, related_name='organizer', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
	     return self.title
   



class CartManager(models.Manager):
    def create_cart(self, user):
        cart = self.create(user = user)
        return cart

class Cart(models.Model):
    cart_id = models.AutoField(primary_key=True)
    user = models.OneToOneField(CustomUser, on_delete = models.CASCADE)
    created_on = models.DateTimeField(default=timezone.now)

    objects = CartManager()

    def subtotal(self):
        events_in_cart = EventInCart.objects.filter(cart=self)
        total = 0
        for event_in_cart in events_in_cart:
            total += event_in_cart.event.price * event_in_cart.quantity
        return total

    def __str__(self):
	    return f"Cart for {self.user.name}"

class EventInCart(models.Model):
    class Meta:
        unique_together = (('cart', 'event'),)
    event_in_cart_id = models.AutoField(primary_key=True)
    cart = models.ForeignKey(Cart, on_delete = models.CASCADE)
    event = models.ForeignKey(Event, on_delete = models.CASCADE)
    quantity = models.PositiveIntegerField()


    def __str__(self):
	     return f"Event: {self.event.title}"


class Payment(models.Model):
    pidx = models.CharField(max_length=100)
    transaction_id = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    mobile = models.CharField(max_length=20)
    purchase_order_id = models.CharField(max_length=100)
    purchase_order_name = models.CharField(max_length=100)
    status = models.CharField(max_length=20)

'''

class OtpModel(models.Model):
    otp_regex = RegexValidator( regex = r'^\d{6}$',message = "otp should be in six digits")
    otp = models.CharField(max_length=6, validators=[otp_regex])
    phone_regex = RegexValidator( regex = r'^\d{10}$',message = "phone number should exactly be in 10 digits")
    phone = models.CharField(max_length=255, validators=[phone_regex])
    expiry = models.DateTimeField(default = (timezone.now() + timedelta(minutes = 5)))
    is_verified = models.BooleanField(default=False)
    
'''    

organizer/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, ReadOnlyPasswordHashField
from .models import CustomUser, Organizer, OrganizerAdditional, Event, EventInCart, AudienceAdditional
from django.core.exceptions import ValidationError 
from django.core.validators import RegexValidator
import zoneinfo

from bootstrap_datepicker_plus.widgets import DatePickerInput, TimePickerInput

from timezone_field import TimeZoneFormField
from tinymce.widgets import TinyMCE

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

class AudienceProfileForm(forms.ModelForm):
    class Meta:
        model = AudienceAdditional
        fields = ['profile_picture']

        
class RegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = [
            'email',
            'name',
            'password1',
            'password2',
        ]

'''
class RegistrationFormSeller(UserCreationForm):
    
    phone_regex = RegexValidator( regex = r'^\d{10}$',message = "phone number should exactly be in 10 digits")
    phone = forms.CharField(max_length=255, validators=[phone_regex])
    timezone = TimeZoneFormField(choices_display="WITH_GMT_OFFSET")
    class Meta:
        model = Organizer
        fields = [
            'email',
            'name',
            'password1',
            'password2',
            'phone',
            'timezone'
        ]        
'''

class RegistrationFormSeller2(forms.ModelForm):
    class Meta:
        model = OrganizerAdditional
        fields = [
            'phone',
            'address',
        ]

class EventCreation(forms.ModelForm):
    class Meta:
        model = Event
        widgets = {'content': TinyMCE(attrs={'cols': 40, 'rows': 20}),
                   "start_date": DatePickerInput(),
                   "end_date": DatePickerInput(range_from="start_date"),
                   "start_time": TimePickerInput(),
                   }
        fields = [
            'title',
            'event_description',
            'start_date',
            'end_date',
            'start_time',
            'category',
            'venue',
            'capacity',
            'image',
            'price'
        ]


class CartForm(forms.ModelForm):
    class Meta:
        model = EventInCart
        fields = [
            'quantity'
        ]

class PaymentForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    phone = forms.CharField(max_length=20)
    amount = forms.DecimalField(max_digits=10, decimal_places=2)
'''
class SendOtpBasicForm(forms.Form):
    phone_regex = RegexValidator( regex = r'^\d{10}$',message = "phone number should exactly be in 10 digits")
    phone = forms.CharField(max_length=255, validators=[phone_regex])

    class Meta:
        fields = [
            'phone',
        ]

class VerifyOtpBasicForm(forms.Form):
    otp_regex = RegexValidator( regex = r'^\d{4}$',message = "otp should be in six digits")
    otp = forms.CharField(max_length=6, validators=[otp_regex])

    # class Meta:
    #     field




'''

templates/organizer/basic.html
<!doctype html>
<html lang="en">
{% load hosts %}
{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap package -->
    <title>{% block title %}{% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css?family=Roboto|Acme|Rubik" rel="stylesheet" />

    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.min.css" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="{% static 'organizer/css/organizer.css' %}" rel="stylesheet">



    {% block css %}{% endblock %}
</head>

<body>
    
    {% block body %}
    {% endblock %}



    <!-- Option 1: Bootstrap Bundle with Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-popRpmFF9JQgExhfw5tZT4I9/CI5e2QcuUZPOVXb1m7qUmeR2b50u+YFEYe1wgzy"
        crossorigin="anonymous"></script>


    <!-- MDB -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.umd.min.js"></script>




</body>
{% block js %}
{% endblock %}

</html>

templates/organizer/create_event.html
{% extends 'organizer/basic.html' %}
{% load static %}
{% load hosts %}
{% load myfilters %}
{% block title %}
{% endblock %}

{% block css %}
<style>
    body{
        background-color:#f5f5f5;

    }
.main-area{
    display: flex;
    align-items: center;
}
.event-form{
    width:100%;
    max-width: 800px;
    margin:auto;
    margin-top:40px;
    padding:20px;
    background-color: #fff;
    border-top: 5px solid #2BA977;
    border-radius: 5px;
}
.mainheading{
    text-align: center;
}
</style>
{% endblock %}

{% block body%}

<form method="POST" enctype="multipart/form-data">{% csrf_token %}
    <div class="main-area">
        <div class="event-form">
            {{ form.non_field_errors }}
            <h2 class="mainheading custom-text-2">Event Form</h2>
            
            <label for="id_title" class="login-labels">Event Title</label>
            {{ form.title.errors }}
            {{ form.title|addclass:'form-control'|addplaceholder:'Event Name Or Title'}}

            <label for="id_event_description" class="login-labels">Description</label>
            {{ form.event_description.errors }}
            {{ form.event_description|addclass:'form-control'|addplaceholder:'Description' }}
           
            <label for="id_start_date" class="login-labels">Start Date</label>
            {{ form.start_date.errors }}
            {{ form.start_date|addclass:'form-control'|addplaceholder:'start date'}}
            
            <label for="id_end_date" class="login-labels">Ending Date</label>
            {{ form.end_date.errors }}
            {{ form.end_date|addclass:'form-control'|addplaceholder:'end date'}}

            <label for="id_start_time" class="login-labels">Start time</label>
            {{ form.start_time.errors }}
            {{ form.start_time|addclass:'form-control'|addplaceholder:'start time'}}

            <label for="id_category" class="login-labels">Event Category</label>
            {{ form.category.errors }}
            {{ form.category|addclass:'form-control'|addplaceholder:'Event Name Or Title'}}

            <label for="id_venue" class="login-labels">Venue</label>
            {{ form.venue.errors }}
            {{ form.venue|addclass:'form-control'|addplaceholder:'Event Name Or Title'}}

            <label for="id_capacity" class="login-labels">Event Capacity</label>
            {{ form.capacity.errors }}
            {{ form.capacity|addclass:'form-control'|addplaceholder:'Event Name Or Title'}}

            <label for="id_image" class="login-labels">Event Image</label>
            {{ form.image.errors }}
            {{ form.image|addclass:'form-control'|addplaceholder:'Event Name Or Title'}}

            <label for="id_price" class="login-labels">Ticket Price</label>
            {{ form.price.errors }}
            {{ form.price|addclass:'form-control'|addplaceholder:'Event Name Or Title'}}

            <br>
            <div class="form-buttons">
                <input type="submit" value="Save" class="btn custom-btn-1"/>
                <a href="{% url 'dashboard' %}" class="btn btn-outline">Cancel</a>
            </div>
            <br>
            <br>
            
        </div>
    </div>

</form>
{{ form.media }}

{% endblock %}

templates/organizer/register.html
{% extends 'organizer/basic.html' %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
    body{
        background-color:#f5f5f5;

    }
.main-area{
    display: flex;
    align-items: center;
}
.register-form{
    width:100%;
    max-width: 500px;
    margin:auto;
    margin-top:40px;
    padding:20px;
    background-color: #fff;
    border-top: 5px solid #ffb100;
    border-radius: 5px;
}
.mainheading{
    text-align: center;
}
.errorlist{
    color:red;
}
.signup-button{
    background-color: #ffb100;
    border-color: #ffb100;
}
.signup-button:hover{
    background-color: #ffb100;
    border-color: #ffb100;
}
.signup-button:focus{
    background-color: #ffb100;
    border-color: #ffb100;
}

</style>
{% endblock %}

{% block body%}
<form method="POST">{% csrf_token %}
<div class="main-area">
<div class="register-form">
{{ form.non_field_errors }}
     <h2 class="mainheading">EventSafari</h2>
     <h4 class="mainheading">Sign Up For Organizer</h4>
     <label for="id_phone" class="login-labels">Phone*</label> 
     {{ form.phone.errors }}
     {{ form.phone|addclass:'form-control'|addplaceholder:'phone number' }}
     <label for="id_address" class="login-labels">Address*</label> 
     {{ form.address.errors }}
     {{ form.address|addclass:'form-control'|addplaceholder:'Address' }}
     <br>
<button type="submit" class="btn btn-primary btn-lg signup-button">Signup</button>
</form>
</div>
</div>
{% endblock %}

templates/organizer/registerbaseuser.html
{% extends 'main/basic.html' %}
{% load hosts %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
    body {
        background-color: #f5f5f5;

    }

    #intro {
        background-image: url("/media/images/signup-bg.jpg");
        height: 100vh;
    }


    

    .main-area {
        display: flex;
        align-items: center;
    }

    .register-form {
        width: 100%;
        max-width: 500px;
        margin: auto;
        margin-top: 40px;
        padding: 20px;
        background-color: #fff;
        box-shadow: #f5f5f5;
        border-radius: 5px;
    }

    .custom-btn-2 {
        border: 2px solid #006241;
        border-radius: 30px;
        font-family: Acme !important;
        color: #006241;
        font-weight: 500;
    }

    .mainheading {
        text-align: center;
    }

    h2 {
        color: #27592d !important;
        font-family: Acme !important;
        font-size: xx-large;
    }

    .errorlist {
        color: red;
    }

    
</style>
{% endblock %}

{% block body%}
<div id="intro" class="bg-image shadow-2-strong">
    <div class="mask d-flex align-items-center" style="background-color: rgba(0, 0, 0, 0.6);">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-5 col-md-8">
                    <form method="POST">{% csrf_token %}
                        <div class="main-area">
                            <div class="register-form">

                                <h2 class="mainheading custom-text-2">Welcome !</h2>
                                <h5 class="mainheading custom-text-2">Sign Up</h5>
                                <p class="errorlist">{{ form.non_field_errors }}</p>
                                <label for="id_email" class="login-labels">Email Address*</label>
                                {{ form.email.errors }}
                                {{ form.email|addclass:'form-control'|addplaceholder:'Email Address'}}

                                <label for="id_name" class="login-labels">Name*</label>
                                {{ form.name.errors }}
                                {{ form.name|addclass:'form-control'|addplaceholder:'Your Name' }}
                                <label for="id_password1" class="login-labels">Password*</label>
                                {{ form.password1.errors }}
                                {{ form.password1|addclass:'form-control'|addplaceholder:'Your Password' }}
                                <label for="id_password2" class="login-labels">Password Confirmation*</label>
                                {{ form.password2.errors }}
                                {{ form.password2|addclass:'form-control'|addplaceholder:'Your Password' }}
                                <br>
                                <button type="submit" class="btn custom-btn-1"><b>Sign Up</b></button>

                                <br>
                                <br>
                                Already have an account? Login <a
                                    href="{% host_url 'login' host 'services' %}"><strong>here</strong></a> !
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/organizer/update_view.html
{% extends 'organizer/basic.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
<script src="{% static 'bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'bootstrap-datepicker/js/locales/bootstrap-datepicker.en.min.js' %}"></script>
{% load hosts %}
{% load myfilters %}
{% block title %}
{% endblock %}

{% block css %}
<style>
    body{
        background-color:#f5f5f5;

    }
.main-area{
    display: flex;
    align-items: center;
}
.event-form{
    width:100%;
    max-width: 800px;
    margin:auto;
    margin-top:40px;
    padding:20px;
    background-color: #fff;
    border-top: 5px solid #2BA977;
    border-radius: 5px;
}
.mainheading{
    text-align: center;
}
</style>
{% endblock %}

{% block body%}

<form method="POST" enctype="multipart/form-data">{% csrf_token %}
    <div class="main-area">
        <div class="event-form">
            {{ form.non_field_errors }}
            <h2 class="mainheading custom-text-2">Event Form</h2>
            
            <label for="id_title" class="login-labels">Event Title</label>
            {{ form.title.errors }}
            {{ form.title|addclass:'form-control'|addplaceholder:'Event Name Or Title'}}
            <br>

            <label for="id_event_description" class="login-labels">Description</label>
            {{ form.event_description.errors }}
            {{ form.event_description|addclass:'form-control'|addplaceholder:'Description' }}
            <br>

            <label for="id_category" class="login-labels">Event Category</label>
            {{ form.category.errors }}
            {{ form.category|addclass:'form-control'|addplaceholder:'Event Category'}}
           
            <label for="id_start_date" class="login-labels">Start Date</label>
            {{ form.start_date.errors }}
            {{ form.start_date|addclass:'form-control'|addplaceholder:'start date'}}
            
            <label for="id_end_date" class="login-labels">Ending Date</label>
            {{ form.end_date.errors }}
            {{ form.end_date|addclass:'form-control'|addplaceholder:'end date'}}

            <label for="id_start_time" class="login-labels">Start time</label>
            {{ form.start_time.errors }}
            {{ form.start_time|addclass:'form-control'|addplaceholder:'start time'}}

            

            <label for="id_venue" class="login-labels">Venue</label>
            {{ form.venue.errors }}
            {{ form.venue|addclass:'form-control'|addplaceholder:'Event Venue'}}

            <label for="id_capacity" class="login-labels">Event Capacity</label>
            {{ form.capacity.errors }}
            {{ form.capacity|addclass:'form-control'|addplaceholder:'Event Capacity'}}

            <label for="id_image" class="login-labels">Event Image</label>
            {{ form.image.errors }}
            {{ form.image|addclass:'form-control'|addplaceholder:'Event Image'}}

            <label for="id_price" class="login-labels">Ticket Price</label>
            {{ form.price.errors }}
            {{ form.price|addclass:'form-control'|addplaceholder:'Ticket Price'}}

            <br>
            <div class="form-buttons">
                <input type="submit" value="Save" class="btn custom-btn-1"/>
                <a href="{% url 'dashboard' %}" class="btn btn-outline">Cancel</a>
            </div>
            <br>
            <br>
            
        </div>
    </div>

</form>
<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
{{ form.media }}

{% endblock %}